package network.t0.cli;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Creates the .env file with generated keys and default configuration.
 */
public final class EnvFileWriter {

    private EnvFileWriter() {
        // Utility class
    }

    /**
     * Writes the .env file with the generated keypair and default configuration.
     *
     * @param targetDir the project directory
     * @param keyPair   the generated keypair
     * @throws IOException if writing fails
     */
    public static void write(Path targetDir, KeyGenerator.KeyPair keyPair) throws IOException {
        String content = """
            # T-0 Network Provider Configuration
            # Generated by T-0 Provider Init CLI

            # Your provider's private key (DO NOT SHARE)
            PROVIDER_PRIVATE_KEY=%s

            # Your provider's public key (share with T-0 team)
            # Public key: 0x%s

            # T-0 Network's public key (provided by T-0 team)
            NETWORK_PUBLIC_KEY=

            # T-0 Network API endpoint
            TZERO_ENDPOINT=https://api-sandbox.t-0.network

            # Port for your provider server
            PORT=8080

            # Quote publishing interval in milliseconds (recommended: 5000)
            QUOTE_PUBLISHING_INTERVAL=5000
            """.formatted(keyPair.privateKeyHex(), keyPair.publicKeyHex());

        Files.writeString(targetDir.resolve(".env"), content);
    }
}
